In [95]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [96]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('listings_Ottawa.csv')
data.head(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,host_url,host_profile_id,host_profile_url,host_name,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,price_quote_raw,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,261065,https://www.airbnb.com/rooms/261065,20260624160311,2026-06-24,city scrape,Westboro Village Executive Suite,A tastefully decorated and well equipped upper...,NaN,https://a0.muscache.com/pictures/airflow/Hosti...,1369632,https://www.airbnb.com/users/show/1369632,1462543953923126865,https://www.airbnb.com/users/profile/146254395...,Glenn,NaN,14,7,14,7,"Ottawa, Canada",My adventurous spirit was awakened when I went...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/users/1369632/profi...,NaN,1,NaN,NaN,t,t,NaN,Kitchissippi,NaN,45.39084,-75.75621,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,3.0,"[""Drying rack for clothing"", ""Sound system"", ""...",$211.33,2026-07-14,2026-07-17,634.00,211.33,"{""quote"": {""taxes"": null, ""currency"": ""CAD"", ""...",3.0,180.0,3.0,3.0,180.0,180.0,3.0,180.0,NaN,t,5,6,13,118,2026-06-24,133,18,2,64,21,108,22824.0,2011-12-24,2026-06-22,4.95,4.98,4.98,4.98,4.95,4.95,4.91,STR-825-691,NaN,1,1,0,0,0.75
1,290033,https://www.airbnb.com/rooms/290033,20260624160311,2026-06-24,city scrape,Rural charm close to the city,Close to Strathmere and other wedding venues. ...,NaN,https://a0.muscache.com/pictures/3016522/1e453...,415201,https://www.airbnb.com/users/show/415201,1462517811711820670,https://www.airbnb.com/users/profile/146251781...,Daniel,NaN,15,3,14,6,"Ottawa, Canada",Working professional. Living with teenager. Li...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/users/415201/profil...,NaN,1,NaN,NaN,t,t,NaN,Rideau-Goulbourn,NaN,45.16820,-75.71208,Entire home,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Microwave"", ""Refrigerator"", ""Smoke alarm"", ""...",$224.81,2026-07-02,2026-07-04,449.62,224.81,"{""quote"": {""taxes"": null, ""currency"": ""CAD"", ""...",2.0,14.0,2.0,2.0,14.0,14.0,2.0,14.0,NaN,t,23,53,83,149,2026-06-24,22,10,2,149,8,60,13489.0,2013-02-19,2026-05-29,5.00,5.00,4.95,4.95,4.95,5.00,4.91,STR-834-339,NaN,1,1,0,0,0.14
2,490182,https://www.airbnb.com/rooms/490182,20260624160311,2026-06-24,city scrape,Cozy Basement Studio Old Ottawa East,NaN,NaN,https://a0.muscache.com/pictures/5a7e6363-5b91...,2401179,https://www.airbnb.com/users/show/2401179,1462594101497536111,https://www.airbnb.com/users/profile/146259410...,Ela,NaN,14,1,14,1,NaN,We love to slow travel throughout the world wi...,NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/users/2401179/profi...,NaN,3,NaN,NaN,t,t,NaN,Capital,NaN,45.40550,-75.67612,Private room in home,Private room,1,1.0,1 private bath,NaN,1.0,"[""Drying rack for clothing"", ""Microwave"", ""Ref...",$67.13,2026-08-02,2026-09-01,2013.93,67.13,"{""quote"": {""taxes"": null, ""currency"": ""CAD"", ""...",30.0,365.0,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,0,21,51,326,2026-06-24,12,3,1,152,2,180,12083.0,2018-04-29,2026-05-31,5.00,5.00,5.00,5.00,5.00,4.92,4.83,NaN,NaN,1,0,1,0,0.12
3,674799,https://www.airbnb.com/rooms/674799,20260624160311,2026-06-24,city scrape,Up to 3-bdrm with privacy - quiet & safe,"Friendly, responsive hosting, convenient locat...",NaN,https://a0.muscache.com/pictures/39672e5f-36f6...,2058676,https://www.airbnb.com/users/show/2058676,1462585318602893984,https://www.airbnb.com/users/profile/146258531...,William,NaN,14,2,14,2,"Ottawa, Canada",We have been living in Ottawa for years. I wor...,NaN,NaN,NaN,f,NaN,https://a0.muscache.com/im/pictures/user/92bb7...,NaN,1,NaN,NaN,t,t,NaN,Gloucester-South Nepean,NaN,45.26910,-75.72197,Entire rental unit,Entire home/apt,6,1.0,1 bath,5.0,4.0,"[""Refrigerator"", ""Smoke alarm"", ""Wifi"", ""Kitch...",$168.50,2026-07-03,2026-07-05,337.00,168.50,"{""quote"": {""taxes"": null, ""currency"": ""CAD"", ""...",1.0,90.0,1.0,2.0,90.0,90.0,1.3,90.0,NaN,t,17,45,75,350,2026-06-24,115,19,3,176,15,114,19209.0,2013-07-02,2026-06-12,4.66,4.68,4.79,4.82,4.81,4.73,4.65,STR-827-424,NaN,1,1,0,0,0.73
4,682632,https://www.airbnb.com/rooms/682632,20260624160311,2026-06-24,city scrape,"Adorable 2 bdrm, Central Ottawa PD1","This an adorable property with two bedrooms, f...",NaN,https://a0.muscache.com/pictures/3dac520b-19e2...,3201295,https://www.airbnb.com/users/show/3201295,1462622442416896913,https://www.airbnb.com/users/profile/146262244...,Greg And Valerie,NaN,13,10,13,10,"Ottawa, Canada","Hi! I'm Greg, Calgary born and happily transpl...",NaN,NaN,NaN,t,NaN,https://a0.muscache.com/im/users/3201295/profi...,NaN,8,NaN,NaN,t,t,NaN,Kitchissippi,NaN,45.40455,-75.73130,Entire home,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Refrigerator"", ""Smoke alarm"", ""Wifi"", ""Kitch...",$98.06,2027-01-18,2027-02-18,3040.00,98.06,"{""quote"": {""taxes"": null, ""currency"": ""CAD"", ""...",31.0,180.0,31.0,31.0,180.0,180.0,31.0,180.0,NaN,t,0,0,0,150,2026-06-24,11,0,0,16,2,0,0.0,2015-10-25,2025-06-15,4.82,4.73,4.91,4.91,4.91,4.91,4.73,NaN,NaN,8,4,4,0,0.08

In [97]:
#Verificamos información del DataFrame
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2727 entries, 0 to 2726
Data columns (total 90 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            2727 non-null   int64
 1   listing_url                                   2727 non-null   str
 2   scrape_id                                     2727 non-null   int64
 3   last_scraped                                  2727 non-null   str
 4   source                                        2727 non-null   str
 5   name                                          2727 non-null   str
 6   description                                   2696 non-null   str
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   2727 non-null   str
 9   host_id                                       2727 non-null   int64
 10  host_url                                      2727 non-null   str
 11  host_profile_id                               2727 non-null   int64
 12  host_profile_url                              2727 non-null   str
 13  host_name                                     2727 non-null   str
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      2727 non-null   int64
 16  hosts_time_as_user_months                     2727 non-null   int64
 17  hosts_time_as_host_years                      2727 non-null   int64
 18  hosts_time_as_host_months                     2727 non-null   int64
 19  host_location                                 2024 non-null   str
 20  host_about                                    1254 non-null   str
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             2727 non-null   str
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              2727 non-null   str
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           2727 non-null   int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          2727 non-null   str
 32  host_identity_verified                        2727 non-null   str
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        2727 non-null   str
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      2727 non-null   float64
 37  longitude                                     2727 non-null   float64
 38  property_type                                 2727 non-null   str
 39  room_type                                     2727 non-null   str
 40  accommodates                                  2727 non-null   int64
 41  bathrooms                                     2264 non-null   float64
 42  bathrooms_text                                2723 non-null   str
 43  bedrooms                                      1945 non-null   float64
 44  beds                                          2359 non-null   float64
 45  amenities                                     2727 non-null   str
 46  price                                         2484 non-null   str
 47  price_quote_checkin_date                      2527 non-null   str
 48  price_quote_checkout_date                     2527 non-null   str
 49  price_quote_total_price                       2483 non-null   float64
 50  price_quote_price_per_night                   2483 non-null   float64
 51  price_quote_raw                               2527 non-null   str
 52  minimum_nights                                2725 non-null   float64
 53  maximum_nights                                2725 non-null   float64
 54  minimum_minimum_nights                        2725 non-null   float64
 55  maximum_minimum_nights                        2725 non-null   float64
 56  minimum_maximum_nights                        2725 non-null   float64
 57  maximum_maximum_nights                        2725 non-null   float64
 58  minimum_nights_avg_ntm                        2727 non-null   float64
 59  maximum_nights_avg_ntm                        2727 non-null   float64
 60  calendar_updated                              0 non-null      float64
 61  has_availability                              2696 non-null   str
 62  availability_30                               2727 non-null   int64
 63  availability_60                               2727 non-null   int64
 64  availability_90                               2727 non-null   int64
 65  availability_365                              2727 non-null   int64
 66  calendar_last_scraped                         2727 non-null   str
 67  number_of_reviews                             2727 non-null   int64
 68  number_of_reviews_ltm                         2727 non-null   int64
 69  number_of_reviews_l30d                        2727 non-null   int64
 70  availability_eoy                              2727 non-null   int64
 71  number_of_reviews_ly                          2727 non-null   int64
 72  estimated_occupancy_l365d                     2727 non-null   int64
 73  estimated_revenue_l365d                       2484 non-null   float64
 74  first_review                                  2174 non-null   str
 75  last_review                                   2174 non-null   str
 76  review_scores_rating                          2174 non-null   float64
 77  review_scores_accuracy                        2174 non-null   float64
 78  review_scores_cleanliness                     2174 non-null   float64
 79  review_scores_checkin                         2174 non-null   float64
 80  review_scores_communication                   2174 non-null   float64
 81  review_scores_location                        2174 non-null   float64
 82  review_scores_value                           2174 non-null   float64
 83  license                                       1615 non-null   str
 84  instant_bookable                              0 non-null      float64
 85  calculated_host_listings_count                2727 non-null   int64
 86  calculated_host_listings_count_entire_homes   2727 non-null   int64
 87  calculated_host_listings_count_private_rooms  2727 non-null   int64
 88  calculated_host_listings_count_shared_rooms   2727 non-null   int64
 89  reviews_per_month                             2174 non-null   float64
dtypes: float64(37), int64(24), str(29)
memory usage: 1.9 MB

In [98]:
#Ajustar maximo de columnas
pd.options.display.max_columns=None

In [99]:
data.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [100]:
data.shape

(2727, 90)

In [101]:
#Realizamos una copia del dataframe
data2=data.copy()

In [102]:
pd.options.display.max_columns=None

In [103]:
data2.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_profile_id', 'host_profile_url', 'host_name',
       'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [104]:
#Quita columnas que no tienen info/ valores
data2=data2.dropna(axis=1, how='all')

In [105]:
data2.shape

(2727, 77)

In [106]:
data2.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'picture_url', 'host_id', 'host_url', 'host_profile_id',
       'host_profile_url', 'host_name', 'hosts_time_as_user_years',
       'hosts_time_as_user_months', 'hosts_time_as_host_years',
       'hosts_time_as_host_months', 'host_location', 'host_about',
       'host_is_superhost', 'host_picture_url', 'host_listings_count',
       'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood_cleansed', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms',
       'beds', 'amenities', 'price', 'price_quote_checkin_date',
       'price_quote_checkout_date', 'price_quote_total_price',
       'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights',
       'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='str')

In [107]:
NewColumns=['id','last_scraped', 'name', 'host_id', 'host_name', 'hosts_time_as_user_years', 'hosts_time_as_user_months',
       'hosts_time_as_host_years', 'hosts_time_as_host_months',
    'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'price_quote_checkin_date', 'price_quote_checkout_date',
       'price_quote_total_price', 'price_quote_price_per_night',
       'price_quote_raw', 'minimum_nights', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

In [108]:
NewColumns=['id',
            'last_scraped',
            'source', 
            'name',
           'host_id',
        'host_name',
          'hosts_time_as_user_years',
       'hosts_time_as_user_months',
         'hosts_time_as_host_years',
       'hosts_time_as_host_months',
         'host_location', 
       'host_is_superhost',
       'host_listings_count',
      'host_identity_verified',
       'neighbourhood_cleansed',
         'latitude',
           'longitude',
             'property_type',
       'room_type',
         'accommodates', 
         'bathrooms', 
          'bedrooms',
       'beds',
           'price', 
           'price_quote_checkin_date',
       'price_quote_checkout_date',
         'price_quote_total_price',
       'price_quote_price_per_night',
           'minimum_nights',
       'maximum_nights',
       'has_availability',
       'availability_30', 
       'availability_60',
         'availability_90',
       'availability_365',
         'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm',
       'number_of_reviews_ly',
       'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
        'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'reviews_per_month','calculated_host_listings_count', 'calculated_host_listings_count_entire_homes']

In [109]:
len(NewColumns)

50

In [110]:
data2[NewColumns].shape

(2727, 50)

In [111]:
data3=data2[NewColumns]

In [112]:
data3.shape

(2727, 50)

In [113]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 2727 entries, 0 to 2726
Data columns (total 50 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   id                                           2727 non-null   int64
 1   last_scraped                                 2727 non-null   str
 2   source                                       2727 non-null   str
 3   name                                         2727 non-null   str
 4   host_id                                      2727 non-null   int64
 5   host_name                                    2727 non-null   str
 6   hosts_time_as_user_years                     2727 non-null   int64
 7   hosts_time_as_user_months                    2727 non-null   int64
 8   hosts_time_as_host_years                     2727 non-null   int64
 9   hosts_time_as_host_months                    2727 non-null   int64
 10  host_location                                2024 non-null   str
 11  host_is_superhost                            2727 non-null   str
 12  host_listings_count                          2727 non-null   int64
 13  host_identity_verified                       2727 non-null   str
 14  neighbourhood_cleansed                       2727 non-null   str
 15  latitude                                     2727 non-null   float64
 16  longitude                                    2727 non-null   float64
 17  property_type                                2727 non-null   str
 18  room_type                                    2727 non-null   str
 19  accommodates                                 2727 non-null   int64
 20  bathrooms                                    2264 non-null   float64
 21  bedrooms                                     1945 non-null   float64
 22  beds                                         2359 non-null   float64
 23  price                                        2484 non-null   str
 24  price_quote_checkin_date                     2527 non-null   str
 25  price_quote_checkout_date                    2527 non-null   str
 26  price_quote_total_price                      2483 non-null   float64
 27  price_quote_price_per_night                  2483 non-null   float64
 28  minimum_nights                               2725 non-null   float64
 29  maximum_nights                               2725 non-null   float64
 30  has_availability                             2696 non-null   str
 31  availability_30                              2727 non-null   int64
 32  availability_60                              2727 non-null   int64
 33  availability_90                              2727 non-null   int64
 34  availability_365                             2727 non-null   int64
 35  calendar_last_scraped                        2727 non-null   str
 36  number_of_reviews                            2727 non-null   int64
 37  number_of_reviews_ltm                        2727 non-null   int64
 38  number_of_reviews_ly                         2727 non-null   int64
 39  first_review                                 2174 non-null   str
 40  last_review                                  2174 non-null   str
 41  review_scores_rating                         2174 non-null   float64
 42  review_scores_accuracy                       2174 non-null   float64
 43  review_scores_checkin                        2174 non-null   float64
 44  review_scores_communication                  2174 non-null   float64
 45  review_scores_location                       2174 non-null   float64
 46  review_scores_value                          2174 non-null   float64
 47  reviews_per_month                            2174 non-null   float64
 48  calculated_host_listings_count               2727 non-null   int64
 49  calculated_host_listings_count_entire_homes  2727 non-null   int64
dtypes: float64(16), int64(17), str(17)
memory usage: 1.0 MB

In [114]:
valores_nulos=data3.isnull().sum()
valores_nulos

id                                               0
last_scraped                                     0
source                                           0
name                                             0
host_id                                          0
host_name                                        0
hosts_time_as_user_years                         0
hosts_time_as_user_months                        0
hosts_time_as_host_years                         0
hosts_time_as_host_months                        0
host_location                                  703
host_is_superhost                                0
host_listings_count                              0
host_identity_verified                           0
neighbourhood_cleansed                           0
latitude                                         0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms                                      463
bedrooms                                       782
beds                                           368
price                                          243
price_quote_checkin_date                       200
price_quote_checkout_date                      200
price_quote_total_price                        244
price_quote_price_per_night                    244
minimum_nights                                   2
maximum_nights                                   2
has_availability                                31
availability_30                                  0
availability_60                                  0
availability_90                                  0
availability_365                                 0
calendar_last_scraped                            0
number_of_reviews                                0
number_of_reviews_ltm                            0
number_of_reviews_ly                             0
first_review                                   553
last_review                                    553
review_scores_rating                           553
review_scores_accuracy                         553
review_scores_checkin                          553
review_scores_communication                    553
review_scores_location                         553
review_scores_value                            553
reviews_per_month                              553
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
dtype: int64

In [173]:
data3['price_quote_checkin_date'][14]

10

In [122]:
#data3['host_location']       
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto 
data3["host_location"] =data3["host_location"].fillna("Ottawa, Canada")

In [115]:
#Tercer método de sustitución de valores nulos
#Sustituir valores nulos por un valor numérico en  concreto 
data3["first_review"]= data3["first_review"].fillna(10)
data3["last_review"]= data3["last_review"].fillna(10)

In [116]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["review_scores_rating"]=data3["review_scores_rating"].fillna(round(data3["review_scores_rating"].mean(),1))
data3["review_scores_accuracy"]=data3["review_scores_accuracy"].fillna(round(data3["review_scores_accuracy"].mean(),1))
data3["review_scores_checkin"]=data3["review_scores_checkin"].fillna(round(data3["review_scores_checkin"].mean(),1))
data3["review_scores_communication"]=data3["review_scores_communication"].fillna(round(data3["review_scores_communication"].mean(),1))
data3["review_scores_location"]=data3["review_scores_location"].fillna(round(data3["review_scores_location"].mean(),1))
data3["review_scores_value"]=data3["review_scores_value"].fillna(round(data3["review_scores_value"].mean(),1))
data3["reviews_per_month"]=data3["reviews_per_month"].fillna(round(data3["reviews_per_month"].mean(),1))

In [ ]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["bathrooms"]=data3["bathrooms"].fillna(round(data3["bathrooms"].mean(),1))
data3["bedrooms"]=data3["bedrooms"].fillna(round(data3["bedrooms"].mean(),1))
data3["beds"]=data3["beds"].fillna(round(data3["beds"].mean(),1))

In [ ]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["price_quote_total_price"]=data3["price_quote_total_price"].fillna(round(data3["price_quote_total_price"].mean(),1))
data3["price_quote_price_per_night"]=data3["price_quote_price_per_night"].fillna(round(data3["price_quote_price_per_night"].mean(),1))

In [ ]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
data3["price_quote_checkout_date"] =data3["price_quote_checkout_date"].fillna("0000-00-00")

In [182]:
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
##data3["price_quote_checkin_date"] =data3["price_quote_checkin_date"].fillna(10) >> la super regue
data3["price_quote_checkin_date"] = data3["price_quote_checkin_date"].replace(['00:00:00'], "0000-00-00")

In [207]:
data3['price']

0       211.33
1       224.81
2        67.13
3       168.50
4        98.06
         ...
2722    228.39
2723     48.07
2724     57.53
2725    410.00
2726    114.67
Name: price, Length: 2727, dtype: float64

In [ ]:
# Convertir price a número
data3["price"] = data3["price"].str.replace("$", "").str.replace(",", "").astype(float)

#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["price"] = data3["price"].fillna(round(data3["price"].mean(), 1))

In [216]:
#Primer método de sustitución de valores nulos
#Sustituir valores nulos con promedio o media
data3["minimum_nights"] = data3["minimum_nights"].fillna(round(data3["minimum_nights"].mean(), 1))
data3["maximum_nights"] = data3["maximum_nights"].fillna(round(data3["maximum_nights"].mean(), 1))

In [219]:
#has_availability
#Cuarto método de sustitución de valores nulos
#Sustituir valores nulos por un string en  concreto
data3["has_availability"] =data3["has_availability"].fillna("f")

In [220]:
valores_nulos=data3.isnull().sum()
valores_nulos

id                                             0
last_scraped                                   0
source                                         0
name                                           0
host_id                                        0
host_name                                      0
hosts_time_as_user_years                       0
hosts_time_as_user_months                      0
hosts_time_as_host_years                       0
hosts_time_as_host_months                      0
host_location                                  0
host_is_superhost                              0
host_listings_count                            0
host_identity_verified                         0
neighbourhood_cleansed                         0
latitude                                       0
longitude                                      0
property_type                                  0
room_type                                      0
accommodates                                   0
bathrooms                                      0
bedrooms                                       0
beds                                           0
price                                          0
price_quote_checkin_date                       0
price_quote_checkout_date                      0
price_quote_total_price                        0
price_quote_price_per_night                    0
minimum_nights                                 0
maximum_nights                                 0
has_availability                               0
availability_30                                0
availability_60                                0
availability_90                                0
availability_365                               0
calendar_last_scraped                          0
number_of_reviews                              0
number_of_reviews_ltm                          0
number_of_reviews_ly                           0
first_review                                   0
last_review                                    0
review_scores_rating                           0
review_scores_accuracy                         0
review_scores_checkin                          0
review_scores_communication                    0
review_scores_location                         0
review_scores_value                            0
reviews_per_month                              0
calculated_host_listings_count                 0
calculated_host_listings_count_entire_homes    0
dtype: int64

In [221]:
data3[14:]

,id,last_scraped,source,name,host_id,host_name,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,host_location,host_is_superhost,host_listings_count,host_identity_verified,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,price,price_quote_checkin_date,price_quote_checkout_date,price_quote_total_price,price_quote_price_per_night,minimum_nights,maximum_nights,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_ly,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,calculated_host_listings_count,calculated_host_listings_count_entire_homes
14,1908873,2026-07-02,previous scrape,Mer Bleue Private Apartment,9905548,Nadine,12,7,11,2,"Ottawa, Canada",f,1,t,Innes,45.429710,-75.489870,Entire rental unit,Entire home/apt,3,1.4,1.0,2.0,173.30,0000-00-00,"""0000-00-00""",2246.70,173.30,30.0,120.0,t,0,0,0,0,2026-07-02,105,0,0,2015-05-03,2022-03-29,4.87,4.91,4.88,4.88,4.60,4.82,0.77,1,1
15,2148350,2026-06-24,city scrape,Bright Modern & Spacious - Executive Rental,10964947,Trevor,12,5,12,5,"Ottawa, Canada",t,3,t,College,45.342480,-75.784570,Entire home,Entire home/apt,2,1.0,1.0,1.0,125.59,2026-07-19,2026-08-16,3516.54,125.59,28.0,730.0,t,5,35,65,340,2026-06-24,84,4,5,2015-01-30,2026-03-31,4.95,4.96,4.99,5.00,4.88,4.88,0.61,3,3
16,2374455,2026-06-24,city scrape,Charming Eurostyle apartment! PD2,3201295,Greg And Valerie,13,10,13,10,"Ottawa, Canada",t,8,t,Kitchissippi,45.403870,-75.730970,Entire rental unit,Entire home/apt,2,1.0,1.0,1.0,87.94,2026-08-03,2026-09-03,2726.00,87.94,31.0,1125.0,t,0,20,41,104,2026-06-24,26,4,3,2015-09-19,2026-04-30,4.69,4.81,4.85,4.96,4.65,4.65,0.20,8,4
17,2453778,2026-06-24,city scrape,Central Ottawa Micro Condo Studio w Heated Par...,12547161,Evaldo,12,4,12,3,"Ottawa, Canada",t,2,t,Somerset,45.410620,-75.696630,Entire condo,Entire home/apt,2,1.0,2.0,1.0,88.50,2026-09-20,2026-10-20,2655.00,88.50,30.0,365.0,t,2,23,25,300,2026-06-24,312,4,4,2014-03-24,2026-02-12,4.94,4.94,4.97,4.99,4.86,4.85,2.09,1,1
18,2474327,2026-06-24,city scrape,Private unit close to Rideau Canal,12656347,Diem,12,3,11,11,"Ottawa, Canada",t,1,t,Capital,45.408740,-75.680440,Entire guest suite,Entire home/apt,2,1.0,1.0,1.0,184.00,2026-06-30,2026-07-01,184.00,184.00,1.0,1125.0,t,1,5,17,175,2026-06-24,270,37,29,2014-08-19,2026-06-21,4.87,4.90,4.98,4.97,4.90,4.83,1.87,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722,1712500595852321257,2026-06-24,city scrape,Entire 3 Bedroom Home | Park-facing | Private,144913442,Rajal,8,10,2,9,"Ottawa, Canada",f,1,t,Rideau-Goulbourn,45.184202,-75.847425,Entire home,Entire home/apt,6,3.0,3.0,3.0,228.39,2026-08-01,2026-08-31,6851.66,228.39,30.0,1125.0,t,0,22,52,142,2026-06-24,0,0,0,10,10,4.80,4.80,4.90,4.90,4.80,4.70,1.80,1,1
2723,1712704048814715237,2026-06-24,city scrape,Ferngully - A Quiet Room,591441355,Shayne,1,11,1,11,"Ottawa, Canada",f,2,f,Stittsville-Kanata West,45.252740,-75.903540,Private room in home,Private room,1,1.0,1.0,1.0,48.07,2026-06-24,2026-07-24,1442.00,48.07,30.0,90.0,t,30,60,90,365,2026-06-24,0,0,0,10,10,4.80,4.80,4.90,4.90,4.80,4.70,1.80,2,1
2724,1713330988667127498,2026-06-24,city scrape,Studio Steps from University of Ottawa-Sandy Hill,578691557,OĞUzhan,2,1,0,0,"Ottawa, Canada",f,2,t,Rideau-Vanier,45.430658,-75.672800,Entire home,Entire home/apt,2,1.0,1.0,1.0,57.53,2026-06-24,2026-07-24,1726.00,57.53,30.0,365.0,t,30,60,90,365,2026-06-24,0,0,0,10,10,4.80,4.80,4.90,4.90,4.80,4.70,1.80,2,2
2725,1714078106546271800,2026-06-24,city scrape,The Town Home in Downtown Ottawa,590712819,Andre,1,11,1,10,"Ottawa, Canada",f,1,t,Somerset,45.416232,-75.705071,Entire home,Entire home/apt,6,2.5,3.0,3.0,410.00,2026-08-31,2026-09-01,410.00,410.00,1.0,365.0,t,0,0,15,97,2026-06-24,0,0,0,10,10,4.80,4.80,4.90,4.90,4.80,4.70,1.80,1,1
2726,1714089170146930926,2026-06-24,city scrape,Modern 1BR in the Heart of Ottawa,66190971,Luis,10,2,4,8,"Gatineau, Canada",t,64,t,Somerset,45.411516,-75.705157,Entire rental unit,Entire home/apt,2,1.0,1.0,1.0,114.67,2026-06-24,2026-07-24,3439.95,114.67,30.0,365.0,t,30,60,90,270,2026-06-24,0,0,0,10,10,4.80,4.80,4.90,4.90,4.80,4.70,1.80,26,26

In [222]:
#Convertir DataFrame a CSV
data3.to_csv("Ottawa_sin_nulos.csv")